<?php
/**
 * Created by PhpStorm.
 * User: markmcfarlane
 * Date: 2017-05-30
 * Time: 8:52 PM
 */

function pl_client_profile_menu(){
  $items = array();

  $items['admin/config/people/pl-profile/pl-client-profile'] = array(
    'title' => t('Pawsitive Love Client Profile'),
    'description' => t('Pawsitive Love Client Profile Management'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array(0),
    'weight' => 0,
  );

  $items['admin/config/people/pl-profile/pl-client-profile/client/admin'] = array(
    'title' => t('Pawsitive Love Client Profile Form'),
    'description' => t('Client Profile Input Form'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array(0),
    'weight' => 0,
  );

  $items['admin/config/people/pl-profile/pl-client-profile/client/admin/client-edit'] = array(
    'title' => t('Pawsitive Love Client Profile Form'),
    'description' => t('Client Profile Input Form'),
    'type' => MENU_LOCAL_ACTION,
    'access arguments' => array(0),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('client_profile',),
    'file' => 'client_profile.inc',
    'file path' => drupal_get_path('module', 'pl_client_profile'). '/inc/forms',
    'weight' => 1,
    'weight' => 0,
  );

//  $items['admin/config/people/pl-profile/pl-client-profile/client/edit'] = array(
//    'title' => t('Pawsitive Love Client Profile Form'),
//    'description' => t('Client Profile Input Form'),
//    'type' => MENU_LOCAL_TASK,
//    'access arguments' => array(0),
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('client_pet_profile',),
//    'file' => 'client_profile.inc',
//    'file path' => drupal_get_path('module', 'pl_client_profile'). '/inc/forms',
//    'weight' => 1,
//  );

  return $items;
}

function pl_client_profile_entity_info(){
  $items = array();

  $items['pl_client_profile'] = array(
    'label' => t('Pawsitive Love Human Client Profile Entity'),
    'base table' => 'pl_client_human_profile',
    'module' => 'pl_client_profile',
    'entity class' =>  'PL_Client_Human_Profile_Entity',
//    'controller class' => 'PL_Client_Profile_EntityController',
    'metadata controller class' => 'PL_Client_Human_Profile_EntityMetadataController',
//    'views controller class' => 'PL_Client_Human_Profile_ViewsController',
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'cppid',
    ),
    'static cache' => TRUE,
    'label callback' => 'entity_class_label',
  );

  return $items;
}