<?php
/**
 * Created by PhpStorm.
 * User: markmcfarlane
 * Date: 2017-05-30
 * Time: 8:52 PM
 */

function pl_client_profile_menu(){
  $items = array();

  $items['admin/config/system/pl-profile/pl-client-profile'] = array(
    'title' => t('Pawsitive Love Client Profile'),
    'description' => t('Pawsitive Love Client Profile Management'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array(0),
    'weight' => 0,
  );

  $items['example/client-profile'] = array(
    'title' => t('Pawsitive Love Client Profile Form'),
    'description' => t('Client Profile Input Form'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array(0),
    'weight' => 0,
  );

  return $items;
}
