<?php
/**
 * Created by PhpStorm.
 * User: markmcfarlane
 * Date: 2017-05-30
 * Time: 8:52 PM
 */

function pl_employee_profile_menu(){
  $items = array();

  $items['admin/config/people/pl-profile/pl-employee-profile'] = array(
    'title' => t('Pawsitive Love Employee Profile'),
    'description' => t('Pawsitive Love Employee Profile Management'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array(0),
    'weight' => 0,
  );

  return $items;
}
